### PR TITLE
Fix transparency issues

### PR DESCRIPTION
**Pull request by dewert99**
This just switches `FMap::get` to be transparent

### CODE REVIEW

**Comment by dewert99** [comment]
I also found some of `iter::repeat`'s methods should be transparent

**Review by xldenis — APPROVED** [review]

**Comment by xldenis** [comment]
A bunch of sessions are obsolete, too many in fact for it to be your changes (I think). It seems why3 did another big update recently

**Comment by xldenis** [comment]
try rebasing.

**Comment by dewert99** [comment]
You should be good to merge it now

**Pull request merged**
