### PR TITLE
Support deref patterns over box/shrref in logic functions

### PR DESCRIPTION
**Pull request by shiatsumat**
Support deref patterns over box/shrref in logic functions.

### CODE REVIEW

**Comment by shiatsumat** [comment]
This fixes #47.

**Comment by xldenis** [comment]
Can you add a test case for this? 

Just something simple like 

```rust
logic! {
fn test<T>(t : &T) -> T {
match l {
 &t => t
}
}
}
```

**Review by xldenis — APPROVED** [review]
Add a test case and rebase but LGTM

**Comment by shiatsumat** [comment]
I'll add a test case in another PR.

**Pull request merged**
