### PR TITLE
Fix pure neq

### PR DESCRIPTION
**Pull request by jhjourdan**
The logical `!=` operator was not properly translated in impure context.

### CODE REVIEW

**Comment by xldenis** [comment]
Ah, interesting bug, I think this solution is but I wonder if we couldn't just eliminate the `EqualsOrNot` constructor entirely. Perhaps leave a `TODO` expressing that intent?

**Comment by jhjourdan** [comment]
I don't understand. What do you want to replace `EqualsOrNot` with? Why don't you like it?

**Comment by xldenis** [comment]
> I don't understand. What do you want to replace EqualsOrNot with? Why don't you like it?

We already have a `BinaryOp` constructor, so we should use that one for everything instead.

**Comment by jhjourdan** [comment]
#490 : wish granted.

**Pull request merged**
