### PR TITLE
In Rust, vec cannot be larger than isize::MAX

### PR DESCRIPTION
**Pull request by jhjourdan**

### CODE REVIEW

**Comment by xldenis** [comment]
Is this actually part of the spec or just an implementation detail?

**Comment by jhjourdan** [comment]
The documentation of `Vec` is full of things like:

> Panics if the new capacity exceeds isize::MAX bytes.

**Comment by jhjourdan** [comment]
Ah... I have no idea what happens with zero-sized types, though.

**Comment by jhjourdan** [comment]
You're right, for ZST, length can reach `usize::MAX`...

**Pull request closed without merging**
