### PR TITLE
Update rustc to 25-09-2021

### PR DESCRIPTION
**Pull request by xldenis**
This PR updates the toolchain to 25-09-2021, addressing #103. 

This was a slightly challenging update as some crates where broken up and apis were shuffled around. 
However, the test updates are fairly important. It leads me to think if there isn't a way we could have a little more stable ordering of definitions in the test output, we're currently too affected by internal rustc changes.

cc @shiatsumat

### CODE REVIEW

**Review by shiatsumat — APPROVED** [review]
Wow it works! Great!

**Comment by shiatsumat** [comment]
Thank you so much for the very quick update!!
Now `rls` and `rustc-src` work in `aarch64-apple-darwin`, which really helps me.

**Comment by xldenis** [comment]
@shiatsumat i recommend switching from `rls` to `rust-analyzer` it's the replacement and has many more features

**Comment by shiatsumat** [comment]
I switched the VSCode extension from `rust-lang.rust` to `matklad.rust-analyzer`.
Yeah, `rust-analyzer` really provides many nice features! Thanks!

**Pull request merged**
