### PR TITLE
Add type invariants for generic parameters

### PR DESCRIPTION
**Pull request by xldenis**
Rather than taking the approach in #810, we are going to go with this.

### CODE REVIEW

**Comment by xldenis** [comment]
Ok i'll take over this Pr @voidc

**Comment by xldenis** [comment]
Remaining proofs to fix:

- [ ] ../creusot/tests/should_succeed/bdd.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/binary_search.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/hashmap.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/heapsort_generic.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/hillel.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/inplace_list_reversal.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/iterators/03_std_iterators.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/iterators/05_map.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/iterators/06_map_precond.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/iterators/08_collect_extend.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/iterators/10_once.mlcfg ... failure
- [x] ../creusot/tests/should_succeed/iterators/15_enumerate.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/list_reversal_lasso.mlcfg ... failure
- [x] ../creusot/tests/should_succeed/mutex.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/red_black_tree.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/selection_sort_generic.mlcfg ... failure
- [x] ../creusot/tests/should_succeed/sparse_array.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/take_first_mut.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/traits/03.mlcfg ... failure
- [x] ../creusot/tests/should_succeed/traits/13_assoc_types.mlcfg ... failure
- [ ] ../creusot/tests/should_succeed/vector/06_knights_tour.mlcfg ... failure

**Comment by xldenis** [comment]
I've identified that in `06_knights_tour` the issue is the usage of `inv` in the quantifier for `to_ref_seq` blocking things.

**Comment by xldenis** [comment]
`take_first_mut` is broken for unrelated reasons (true on master as well)

**Comment by xldenis** [comment]
`collect_extend` is failing because there is a bug where we resolve an unitialized value leading to an assertion which we cannot prove.

**Comment by jhjourdan** [comment]
Seems like modulo cleaning up sessions, this could be merged?

**Pull request merged**
