### PR TITLE
Remove ghost state from Fuse proof

### PR DESCRIPTION
**Pull request by xldenis**
I realized we don't need ghost state in `Fuse` at all. This also makes it possible to specify the stdlib fuse since we don't introduce a cardinality problem.

### CODE REVIEW

**Comment by jhjourdan** [comment]
The new spec looks good to me... I don't know why we needed this ghost before. That's probably because we used to have a different spec for next in the None case.

**Comment by jhjourdan** [comment]
Before merging, could you please include in your PR the extern_spec change ?

**Comment by jhjourdan** [comment]
> Before merging, could you please include in your PR the extern_spec change ?

?

**Comment by xldenis** [comment]
I had turned on auto-merge and forgot to turn it off, my bad.

**Pull request merged**
