### PR TITLE
Add support for Duration

### PR DESCRIPTION
**Pull request by jhaye**
Spec and test for `Duration`. I'll probably add Traits as needed later (and probably a spec for `Instant`, too). 
This covers all functions for the main impl of the struct, except for the saturating arithmetic operations, which seem to rely on some const function underneath.

### CODE REVIEW

**Comment by jhaye** [comment]
Not sure why `red_black_tree` produces different MLCFG output based on these changes.

**Comment by xldenis** [comment]
Yea there's a weird bug with RBT, I haven't had time to look into it, but spans change erroneously..

**Comment by xldenis** [comment]
Thanks for the PR, I'll take a look in detail Monday, but it looks good at first glance

**Comment by jhjourdan** [comment]
That's a reasonably large contribution, thanks! Could you please sign and send the CLA (for individuals) at the root of the repo? Thanks!

**Comment by xldenis** [comment]
He already emailed it to me

**Comment by jhjourdan** [comment]
Ah, I'm sorry then ;)

**Comment by xldenis** [comment]
Go ahead and update the RBT test with the dummy line changes and this looks good to merge.

**Review by xldenis — APPROVED** [review]

**Pull request merged**
