### PR TITLE
A why3 update broke all the sessions

### PR DESCRIPTION
**Pull request by xldenis**
Update all the proof sessions because of a `why3` update

### CODE REVIEW

**Comment by xldenis** [comment]
cc @jhjourdan

**Comment by jhjourdan** [comment]
What Why3 change is this?

**Comment by jhjourdan** [comment]
I doubt it is mine...

**Comment by xldenis** [comment]
We rebuild why3 every night, the two recent changes that could be responsible are:

- [Take into account vc:do_not_keep_trace in let-rec definitions.](https://gitlab.inria.fr/why3/why3/-/commit/ed1b23fc48d77994b9612ec1578fec88ce657d62)
- [Merge branch 'eliminate_unused_symbols' into 'master'](https://gitlab.inria.fr/why3/why3/-/commit/fad2b7ec3c9a266c84bea40a86225d32836d24c6)

**Comment by xldenis** [comment]
In any case the proofs all pass, we just needed to update the sessions and all current PRs will need to be rebased.

**Comment by jhjourdan** [comment]
Weird... I have no idea why my change had this impact.

**Comment by jhjourdan** [comment]
This should be fixed by #453 .

**Pull request closed without merging**
