### PR TITLE
Relax `still_specializable`

### PR DESCRIPTION
**Pull request by xldenis**
Slightly relaxes the condition on `still_specializable` so that we can see the bodies of default implementations which happened to be used in _final_ trait impls. This addresses the specific case where we have:

```
trait X { predicate foo() { true } } 

impl X for Bar<T> { } 
```

since the `impl` of `X` for `Bar` is not specializable, we should be allowed to open the definition of `foo` in methods where we are using `Bar<T>::foo()`.

### CODE REVIEW

**Comment by jhjourdan** [comment]
If we merge this, are we exposed to evolutions of Rust that would allow more specializations.

**Comment by xldenis** [comment]
> If we merge this, are we exposed to evolutions of Rust that would allow more specializations?

No, this uses the specialization query apis to make sure the definition is `final`. if we bump rust version in manner that would change the result then we will stop specializing as well.

**Comment by jhjourdan** [comment]
Alright, but this means that some proofs will break if this notion of "final" is changed.

**Comment by xldenis** [comment]
> Alright, but this means that some proofs will break if this notion of "final" is changed.

Yes, but if the language changes what it means for something to be specializable, that makes sense that we would (correctly) break affected proofs.

**Pull request merged**
