### PR TITLE
Remove explicit impl Invariant for Once

### PR DESCRIPTION
**Pull request by voidc**
The explicit implementation is no longer needed thanks to #715.

### CODE REVIEW

**Comment by xldenis** [comment]
Note: in the future we may also need / want an invariant on `Once` due to the inner `T` it holds (if only for consistency reasons).

**Comment by xldenis** [comment]
Wait... shouldn't we be required to prove that the result upholds the invariant and thus we need a custom invariant on once?

**Comment by xldenis** [comment]
I think this might be because `Option` doesn't yet have an invariant? Once it does I expect that we will have to give `Once` a real invariant.

**Comment by voidc** [comment]
I think it makes sense to defer adding an invariant on Once until we have a blanket implementation of Invariant.

**Comment by jhjourdan** [comment]
Can we merge this?

**Pull request merged**
